- src/youtube.js
We are getting occasional `Cannot read property 'pauseVideo' of undefined` errors on our webapp while creating and destroying different videojs youtube players. The simple check should fix that.
> Check if ytplayer exists before calling ytplayer.pauseVideo()

- src/youtube.js
There was a problem seeing the playback rate in the pannel
As it is seen in the last picture, there is a delay between changing the playback rate in youtube and the trigger action (ratechange). It is fixed with this pull request
> Fixed trigger to change playback rate

- src/youtube.js
Adds
---
* New labels for 1440p & 2160p, they were appearing as `auto` before
* Add HD / 4K labels to quality buttons
Pics
---
Some slight styles:
No additional styles: 
Unfortunately with the default skin the HD labels is right up against the rest of the label & are lower case ...
> Adding labels for new high res formats,  add HD/4k labels

- bower.json
/srv/dev/bedrock/web/app/themes/hdav$ bower install video.js
bower cached       ...
....
...                                                                                                                                                                                                                                                                                                                                                  video.js#~4.11 which resolved to 4.11.4 and is required by videojs-youtube#1.2.10                                                                            
tests just fine and working on 4.12.6
> Requires 4.11 or ABOVE not 4.11 only

- src/youtube.js
As the controlbar is configurable and the the `playbackRateMenuButton` can be turned off it should be checked if it exists first before calling its `update()` method.
> Make sure playbackRateMenuButton exists before updating it

- src/youtube.js
To give a clear error message on screen in video.js, the error code needs to be converted to a string.
> Convert YouTube errors into text, to improve error reporting.

- src/youtube.js
With this change, we can show video info by setting the the option 'showInfo' to true. It used to be hardcoded to false. It looks like this:
> Enables toggleable video info

- src/Youtube.js
In the current 2.0.0 release, the player always starts playing after a seek. This is very unexpected when the player was paused before starting the seek.
With this pull request, the playback state is retained after the seek:
* The additional `play` and `playVideo` calls in the seek handlers have been removed.
* If the player was paused before the seek, it is paused again after the seek is completed. This is a workaround for a weird quirk in the YouTube player: when starting a seek while buffering, the player always starts playing again after the seek.
This also fixes some other bugs which popped up while working on this change:
* When quickly seeking multiple times in a row, multiple interval timers (to monitor time changes) may be started simultaneously. However, only one of them is …
> Retain playing/paused state after seek

- src/Youtube.js
Hello,
I've had the error `VIDEOJS: ERROR: the “YouTube” tech is undefined. Skipped browser support check for that tech` using `video.js@5.8.1` and `videojs-youtube@2.0.8` along with browserify.
Seems like this error has been fixed by editing the AMD declaration for CommonJS exports.
I don't have the error anymore with this fix!
> update youtube.js to fix the 'youtube' tech is undefined error

- .gitignore
- src/Youtube.js
A number of fixes were made to the YouTube tech to allow it to be used in the Brightcove Player.  Most of these fixes also fix issues which could come up using a videojs player with certain plugins.  Here's a list of everything that was changed:
* Added .idea to the `.gitignore` file to prevent WebStorm files from being added to git
* Ensure the version of videojs we're using has the `getComponent` function before loading the tech
* Added the `vjs-tech` class to the tech element div.  This is used in several plugins with `querySelector` to retrieve the tech element div and is needed when used in a Brightcove Player.
* Added video cueing when switching sources with autoplay disabled.
* Fixed `onPlayerStateChange` by setting `laststate` before triggering any events as some listeners use the …
> Fixes for Brightcove Player and videojs integration

- src/Youtube.js
Destroy the container on dipose.
When you are changing the source beetwen mp4 and youtube videos, the container of the youtube iframe remains over the html5 video tag after the source is changed
> Remove wrapper on dispose

- src/Youtube.js
-webpack builds will now use CommonJS style by default
-fixes #378
> Changed the order of module resolution type checking (fixes #378)

- src/Youtube.js
Error 150 should actually be associated with embed errors (101) rather than not found errors (2 and 100) per https://developers.google.com/youtube/js_api_reference#onError.
> Associate error #150 with #101 

- src/Youtube.js
Features were added to videojs-youtube which allows videos to be loaded once the player is instantiated, however the player is destroyed whenever a player error occurs.  This means that calling `player.src()` with some new video url will no longer work when an error has occurred on the current video.  This PR removes the destruction of the player when an error occurs, and also destroys it properly whenever `dispose()` is called on the tech.
> Don't destroy the YouTube player on error

- README.md
- src/Youtube.js
Right now, the only `playerVars` allowed are those officially documented in the YouTube API. However, there are a bunch of undocumented variables that people might need to set at some point. For example, `wmode` is often needed to make the YouTube iframe behave on older versions of IE.
This PR introduces `customVars` - an option, if provided, that allows undocumented `playerVars` to be set like so:
```
youtube: {
customVars: {
wmode: 'transparent',
},
}
```
> Allow undocumented player parameters via customVars

- src/Youtube.js
The earliest time we can call a player method is the onready handler.
Youtube doesn't support a muted attribute, so, we just call
ytPlayer.mute() at the earlier opportinity when the attribute is set.
Fixes #385.
> fix: support muted attribute

- src/Youtube.js
Because of how we parse the url of the youtube video, start and end
times were getting stripped. However, passing them to the as playerVars
wasn't working for some reason. So, instead, use startSeconds and
endSeconds in load and cue video by id methods.
Fixes #388.
> feat: add support for start and end times.

- src/Youtube.js
- By returning a specific error `code` and `message` videojs will automatically show it on the player. Moreover, devs can also customise this behaviour thanks to the provided unique code.
- By triggering `pause` instead of just stopping the youtube player we ensure that the spinner and others videojs elements are correctly showed/removed on error
> Provide meaningful error messages and correctly stop the video on error

- examples/global-parameters.html
- examples/simple.html
- examples/youtube-controls.html
- examples/youtube-javascript.html
- examples/youtube-list.html
- examples/youtube-playlist.html
- src/Youtube.js
There are errors in the console for this plugin, but it appears they are not a consequence of Video.js 6 - they appear with 5, too.
> Video.js 5/6 cross-compatibility

- src/Youtube.js
there is an exception is you dispose the player while the YT api is not loaded yet. this fix prevent crashs in such edge cases.
> fix: prevent exception when quick dispose and YT not ready yet

- src/Youtube.js
The current implementation of `supportsFullScreen` is just returning `true` (https://github.com/videojs/videojs-youtube/blob/master/src/Youtube.js#L621-L623), which seems to be not functioning well in iOS.  In order to fall back to full window mode in videoJS, I've made some changes to check three vendor `fullscreen` methods.
This would be one possible solution to https://github.com/videojs/videojs-youtube/issues/431.
> adjust full screen support

- src/Youtube.js
without a proper jsdom this fails in jest:
with this safeguard it run fine in jest.
IMHO it's nice to support testability like this.
Setting up a jsdom every time is a needless pain.
> adds an if statement to prevent breaking in jest

- .jshintrc
- package.json
- src/Youtube.js
The videojs.extend() function is removed from Video.js 8.0 See: https://videojs.com/guides/videojs-7-to-8/#videojsextend This patch reworks code to be an ES6 Class.
Fixes #604
Plugin unit tests also pass, and have tested with a videojs 8.0.4 implementation
> Update component to be compatible with VideoJS 8.0.4+
